export const RESTART="RESTART"
export const PAUSE="PAUSE"
export const CHANGE_TURN="CHANGE_TURN"
export const COUNT_DOWN="COUNT_DOWN"
export const PLACE_PUCK="PLACE_PUCK"
export const DECREMENT="DECREMENT"
export const FINISH = "FINISH"
export const END_TURN="END_TURN"